/// Flutter icons JeffIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  JeffIcons
///      fonts:
///       - asset: fonts/JeffIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class JeffIcons {
  JeffIcons._();

  static const _kFontFam = 'JeffIcons';
  static const _kFontPkg = null;

  static const IconData address_book = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData all = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brief = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delivered = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delivery = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pending = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment_1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData premium = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pricelist = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData regular = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delivery_v2 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shorts = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sock = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData washing = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData p_shirt_v2 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sando = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tshirt_v2 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tac_v1 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
